### ISSUE TITLE
Dependency cv2

### ISSUE THREAD

**Issue by mviereck** [hqhoang/mftker#1]
Hello,

I want to try out your tool and get this message:
```
$ ./mftker.py 
Traceback (most recent call last):
  File "/home/lauscher/git3/mftker/./mftker.py", line 12, in <module>
    from cv2 import cv2, countNonZero, cvtColor
ImportError: cannot import name 'cv2' from 'cv2' (/usr/lib/python3/dist-packages/cv2.cpython-39-x86_64-linux-gnu.so)
```
What dependency is missing here?
Running on Debian stable.
I already did:
```
pip3 install Pillow
pip3 install tkinterdnd2
```

**Comment by hqhoang** [comment]
oh sorry, just added ECC alignment last night, forgot to update README :-(

Either one of these should do:

pip install opencv-python
pip install opencv-contrib-python

**Comment by mviereck** [comment]
Now it starts up, thank you!
