### ISSUE TITLE
Window too big

### ISSUE THREAD

**Issue by mviereck** [hqhoang/mftker#2]
Hello,

after startup the application window is too big in width and height.
I can manually reduce the witdh, but not the height. So I have to move the entire window to access the button below, and move again too reach the buttons above.

**Comment by hqhoang** [comment]
dang, I'm on a QHD monitor and set the min size too big. Try editing around line 66, set it to a smaller size:

```
    self.geometry('1600x1000')
    self.minsize(1200, 1000)
```
Let me know which size works best for you. Thanks.

**Comment by mviereck** [comment]
My screen is 1600x900.
I have changed the lines to:
```
    self.geometry('1500x800')
    self.minsize(1200, 800)
```
This works well for me.
I cannot reduce (but enlarge) the height manually although you have declared the window as resizable. Don't know why.
Thank you for the quick response!

**Comment by hqhoang** [comment]
yeah, minsize forces minimum size, so you cannot make the window any smaller what specified in self.minsize()

800 might be too short to display all the options on the left panel of the "Stack" tab. I was thinking about adding a scrollbar there but procrastinated. Will do that tomorrow.

**Comment by mviereck** [comment]
Ok, you are right.
I have to set the min height to 830 to show the "Stack" button below. 
I cannot make the window bigger than that, need some screen height for a panel.

**Comment by mviereck** [comment]
btw, thank you for providing a GUI for enfuse!

I have a stackshot project based on imagemagick, but currently it is asleep. Currently it is a bash script. Some day I want to translate it to python because I need a GUI for some interaction. https://github.com/mviereck/microscopy-tools

**Comment by hqhoang** [comment]
Converted the left pane into scrollable frame (support mouse wheel scrolling, too). Also open the window maximized on start up  (3427dd7)
